import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { Header } from "@/components/header"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-bg" className="dark">
      <body className={inter.className}>
        <ThemeProvider>
          <main className="space-y-5">
            <Header />
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
